# Connessione al database di NightFlow
CONNECTION_URL=jdbc:mysql://localhost:3306/nightflowdb

# Utente base per effettuare il primo accesso (fase di login)
LOGIN_USER=nf_login
LOGIN_PASS=nf_login

CLIENT_USER=nf_cliente
CLIENT_PASS=nf_cliente

ORGANIZER_USER=nf_organizzatore
ORGANIZER_PASS=nf_organizzatore

# SENDGRID
SENDGRID_API_KEY=YOUR_KEY_HERE
SENDGRID_FROM_EMAIL=YOUR_EMAIL_HERE