# Connessione al database di NightFlow
CONNECTION_URL=jdbc:mysql://localhost:3306/nightflowdb

# Utente base per effettuare il primo accesso (fase di login)
LOGIN_USER=nf_login
LOGIN_PASS=nf_login

# Credenziali per il ruolo Cliente
CLIENTE_USER=nf_cliente
CLIENTE_PASS=nf_cliente

# Credenziali per il ruolo Organizzatore
ORGANIZZATORE_USER=nf_organizzatore
ORGANIZZATORE_PASS=nf_organizzatore

# SENDGRID (Mail API per l'invio dei biglietti o conferme)
SENDGRID_API_KEY=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
SENDGRID_FROM_EMAIL=nightflow.appl@gmail.com